-- Hand-written (not generated by `prisma migrate dev`): renames the Project entity to
-- Contract everywhere, preserving existing data via RENAME TABLE / RENAME COLUMN rather
-- than Prisma's default drop-and-recreate diff (which would have deleted the `projects`,
-- `project_audit_logs` and other `project_*` tables and their rows).

-- 1. Rename tables (parent first; MariaDB updates FK metadata automatically).
RENAME TABLE `projects` TO `contracts`;
RENAME TABLE `project_audit_logs` TO `contract_audit_logs`;
RENAME TABLE `project_completion_dates` TO `contract_completion_dates`;
RENAME TABLE `project_documents` TO `contract_documents`;
RENAME TABLE `project_tag_assignments` TO `contract_tag_assignments`;
RENAME TABLE `project_urls` TO `contract_urls`;

-- 2. Rename columns.
ALTER TABLE `contracts` RENAME COLUMN `projectNumber` TO `contractNumber`;
ALTER TABLE `contracts` RENAME COLUMN `projectType` TO `contractType`;

ALTER TABLE `contract_audit_logs` RENAME COLUMN `projectId` TO `contractId`;
ALTER TABLE `contract_audit_logs` RENAME COLUMN `projectNumber` TO `contractNumber`;
ALTER TABLE `contract_audit_logs` RENAME COLUMN `projectName` TO `contractName`;

ALTER TABLE `contract_completion_dates` RENAME COLUMN `projectId` TO `contractId`;
ALTER TABLE `contract_documents` RENAME COLUMN `projectId` TO `contractId`;
ALTER TABLE `contract_tag_assignments` RENAME COLUMN `projectId` TO `contractId`;
ALTER TABLE `contract_urls` RENAME COLUMN `projectId` TO `contractId`;

-- `System.projectType` (the delivered system's own category enum, PMIS/VTS/AIS/...) is a
-- separate concept from the Contract entity, but its name also contains "project".
ALTER TABLE `systems` RENAME COLUMN `projectType` TO `contractType`;

-- 3. Rename indexes to match the new table/column names.
ALTER TABLE `contracts` RENAME INDEX `projects_currencyId_idx` TO `contracts_currencyId_idx`;
ALTER TABLE `contracts` RENAME INDEX `projects_deleted_idx` TO `contracts_deleted_idx`;
ALTER TABLE `contracts` RENAME INDEX `projects_systemId_idx` TO `contracts_systemId_idx`;
ALTER TABLE `contracts` RENAME INDEX `projects_projectNumber_key` TO `contracts_contractNumber_key`;

ALTER TABLE `contract_audit_logs` RENAME INDEX `project_audit_logs_action_idx` TO `contract_audit_logs_action_idx`;
ALTER TABLE `contract_audit_logs` RENAME INDEX `project_audit_logs_createdAt_idx` TO `contract_audit_logs_createdAt_idx`;
ALTER TABLE `contract_audit_logs` RENAME INDEX `project_audit_logs_projectId_idx` TO `contract_audit_logs_contractId_idx`;

ALTER TABLE `contract_completion_dates` RENAME INDEX `project_completion_dates_projectId_idx` TO `contract_completion_dates_contractId_idx`;

ALTER TABLE `contract_documents` RENAME INDEX `project_documents_documentTypeId_idx` TO `contract_documents_documentTypeId_idx`;
ALTER TABLE `contract_documents` RENAME INDEX `project_documents_projectId_idx` TO `contract_documents_contractId_idx`;

ALTER TABLE `contract_tag_assignments` RENAME INDEX `project_tag_assignments_projectId_tagId_key` TO `contract_tag_assignments_contractId_tagId_key`;
ALTER TABLE `contract_tag_assignments` RENAME INDEX `project_tag_assignments_tagId_idx` TO `contract_tag_assignments_tagId_idx`;

ALTER TABLE `contract_urls` RENAME INDEX `project_urls_projectId_idx` TO `contract_urls_contractId_idx`;
ALTER TABLE `contract_urls` RENAME INDEX `project_urls_urlTypeId_idx` TO `contract_urls_urlTypeId_idx`;

ALTER TABLE `systems` RENAME INDEX `systems_projectType_idx` TO `systems_contractType_idx`;

-- 4. Rename foreign key constraints (MySQL/MariaDB has no RENAME CONSTRAINT, so drop +
-- recreate with identical ON UPDATE/ON DELETE rules as before).
ALTER TABLE `contracts`
  DROP FOREIGN KEY `projects_currencyId_fkey`,
  DROP FOREIGN KEY `projects_systemId_fkey`,
  ADD CONSTRAINT `contracts_currencyId_fkey` FOREIGN KEY (`currencyId`) REFERENCES `currencies`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  ADD CONSTRAINT `contracts_systemId_fkey` FOREIGN KEY (`systemId`) REFERENCES `systems`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `contract_completion_dates`
  DROP FOREIGN KEY `project_completion_dates_projectId_fkey`,
  ADD CONSTRAINT `contract_completion_dates_contractId_fkey` FOREIGN KEY (`contractId`) REFERENCES `contracts`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `contract_documents`
  DROP FOREIGN KEY `project_documents_documentTypeId_fkey`,
  DROP FOREIGN KEY `project_documents_projectId_fkey`,
  ADD CONSTRAINT `contract_documents_documentTypeId_fkey` FOREIGN KEY (`documentTypeId`) REFERENCES `document_types`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  ADD CONSTRAINT `contract_documents_contractId_fkey` FOREIGN KEY (`contractId`) REFERENCES `contracts`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `contract_tag_assignments`
  DROP FOREIGN KEY `project_tag_assignments_projectId_fkey`,
  DROP FOREIGN KEY `project_tag_assignments_tagId_fkey`,
  ADD CONSTRAINT `contract_tag_assignments_contractId_fkey` FOREIGN KEY (`contractId`) REFERENCES `contracts`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `contract_tag_assignments_tagId_fkey` FOREIGN KEY (`tagId`) REFERENCES `tags`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE `contract_urls`
  DROP FOREIGN KEY `project_urls_projectId_fkey`,
  DROP FOREIGN KEY `project_urls_urlTypeId_fkey`,
  ADD CONSTRAINT `contract_urls_contractId_fkey` FOREIGN KEY (`contractId`) REFERENCES `contracts`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `contract_urls_urlTypeId_fkey` FOREIGN KEY (`urlTypeId`) REFERENCES `url_types`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
